---
title: "L14-code"
author: "Your netid, last name, first name here"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Connect to the database

```{r}
library(DBI)
library(RSQLite)
drv = dbDriver("SQLite") # the driver for the db you want to connect to
chinook_db = dbConnect(drv, # the driver to use
              dbname="./data/Chinook_Sqlite.sqlite") #path to the db file
```


## 1. What does this query do? 

```{r}
dbGetQuery(chinook_db, 
                        "SELECT count(*) FROM track")
```


## 2. What does this query do? 

```{r}
dbListFields(chinook_db, "track")
```

## 3. SELECT

Select the first five records for TrackId, Name,  AlbumId, Milliseconds, Bytes, UnitPrice from Track table

```{r}
dbGetQuery(chinook_db, 
           "SELECT TrackId, Name, AlbumId, Milliseconds, Bytes, UnitPrice
           FROM  track 
           limit 5")
```

## 4. SELECT with Aggregation

```{r}
dbGetQuery(chinook_db, 
     "SELECT AVG(Milliseconds), AVG(Bytes), MAX(UnitPrice)
      FROM Track")
```

## 5. GROUP BY

```{r}
dbGetQuery(chinook_db, "SELECT AlbumId, AVG(Bytes)
                      FROM Track
                      GROUP BY AlbumId
                      ORDER BY AVG(Bytes) DESC
                      LIMIT 10")
```

## 6. AS

```{r}
dbGetQuery(chinook_db, 
           "SELECT AlbumId, AVG(Bytes) AS AvgBytes
            FROM Track
            GROUP BY AlbumId
            ORDER BY AVG(Bytes) DESC
            LIMIT 10")
```

## 7. count, DISTINCT, case insensitive

```{r}
# case insensitive
dbGetQuery(chinook_db, "Select count(DISTINCT(ALBUMID)) FROM track")
```


```{r}
dbGetQuery(chinook_db, 
           "SELECT  AlbumId, Avg(Bytes)
           FROM Track
           WHERE AlbumId = 50")
```

```{r}
dbGetQuery(chinook_db, 
           "SELECT AlbumId, MediaTypeId,AVG(Bytes) as AvgBytes
                      FROM Track
                      WHERE AlbumId <= 160
                      GROUP BY AlbumId
                      ORDER BY AvgBytes DESC
                      LIMIT 10")
```

## 8. HAVING

```{r}
dbGetQuery(chinook_db, 
           "SELECT AlbumId, MediaTypeId,AVG(Bytes) as AvgBytes
            FROM Track
            WHERE AlbumId >= 160
            GROUP BY AlbumId
            HAVING AvgBytes >= 25000000
            ORDER BY AVG(Bytes) DESC
            LIMIT 10")
```

## 9. WHERE, pattern matching

```{r}
dbGetQuery(chinook_db, 
            "SELECT Name, Albumid, composer
              FROM track
              WHERE composer LIKE '%Smith%'
              ORDER BY albumid")
```

## 10. Close db connection 

```{r}
dbDisconnect(chinook_db)
```